import type { ReviewResult, CategoryScore, ReviewIssue } from './types.js';

const STATUS_EMOJI: Record<CategoryScore['status'], string> = {
  excellent: '✅',
  good:      '🟢',
  warning:   '⚠️',
  critical:  '❌',
};

const SEVERITY_EMOJI: Record<ReviewIssue['severity'], string> = {
  critical: '🔴',
  error:    '🟠',
  warning:  '🟡',
  info:     '🔵',
};

/**
 * Generate a complete GitHub-flavored Markdown review report.
 */
export function generateMarkdownReport(result: ReviewResult): string {
  const { totalScore, categories, issues, filesReviewed, hasBreakingChanges, estimatedFixMinutes } = result;

  const scoreEmoji = totalScore >= 90 ? '🚀' : totalScore >= 70 ? '✅' : totalScore >= 50 ? '⚠️' : '❌';
  const lines: string[] = [];

  // Header
  lines.push(`## ${scoreEmoji} ReactPilot Code Review`);
  lines.push('');
  lines.push(`**Score: ${totalScore}/100**`);
  lines.push('');

  // Category table
  lines.push('| Category | Score | Status |');
  lines.push('|---|---|---|');
  for (const cat of categories) {
    const emoji = STATUS_EMOJI[cat.status];
    const label = cat.status.charAt(0).toUpperCase() + cat.status.slice(1);
    const issueCount = cat.issues.length;
    const detail = issueCount > 0 ? ` (${issueCount} issue${issueCount === 1 ? '' : 's'})` : '';
    lines.push(`| ${cat.label} | ${cat.score}/100 | ${emoji} ${label}${detail} |`);
  }
  lines.push('');

  // Meta
  lines.push(`| | |`);
  lines.push(`|---|---|`);
  lines.push(`| **Breaking Changes** | ${hasBreakingChanges ? '⚠️ Detected' : '✅ None'} |`);
  lines.push(`| **Estimated Fix Time** | ${formatTime(estimatedFixMinutes)} |`);
  lines.push(`| **Files Reviewed** | ${filesReviewed.length} |`);
  lines.push('');

  // Issues by category
  if (issues.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## 📋 Issues');
    lines.push('');

    const byCategory = groupByCategory(issues);

    for (const [category, catIssues] of Object.entries(byCategory)) {
      if (catIssues.length === 0) continue;

      const catLabel = categories.find((c) => c.id === category)?.label ?? category;
      lines.push(`<details>`);
      lines.push(`<summary><strong>${catLabel}</strong> — ${catIssues.length} issue(s)</summary>`);
      lines.push('');

      for (const issue of catIssues) {
        const emoji = SEVERITY_EMOJI[issue.severity];
        lines.push(`**${emoji} ${issue.severity.toUpperCase()}** — \`${issue.file}\`${issue.line ? `:${issue.line}` : ''}`);
        lines.push('');
        lines.push(issue.message);

        if (issue.code) {
          lines.push('');
          lines.push('```tsx');
          lines.push(issue.code);
          lines.push('```');
        }

        if (issue.suggestion) {
          lines.push('');
          lines.push(`> 💡 **Fix:** ${issue.suggestion}`);
        }

        lines.push('');
        lines.push('---');
        lines.push('');
      }

      lines.push('</details>');
      lines.push('');
    }
  } else {
    lines.push('> ✅ No issues found in the changed files. Great work!');
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(`*Generated by [ReactPilot](https://github.com/CO-Pratham/reactpilot) on ${new Date().toUTCString()}*`);

  return lines.join('\n');
}

function groupByCategory(issues: ReviewIssue[]): Record<string, ReviewIssue[]> {
  const groups: Record<string, ReviewIssue[]> = {};
  for (const issue of issues) {
    if (!groups[issue.category]) groups[issue.category] = [];
    groups[issue.category].push(issue);
  }
  return groups;
}

function formatTime(minutes: number): string {
  if (minutes < 60) return `${minutes} minute${minutes === 1 ? '' : 's'}`;
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  return `${hours}h ${mins > 0 ? `${mins}m` : ''}`.trim();
}
