import type { MigrationResult, MigrationPlan } from './types.js';

/**
 * Generate a clean markdown summary of the migration run.
 */
export function generateMarkdownReport(
  result: MigrationResult,
  plan: MigrationPlan
): string {
  const lines: string[] = [];

  const title = result.mode === 'react19' ? 'React 19' : 'Next.js';
  lines.push(`# 🚀 ${title} Migration Report`);
  lines.push('');
  lines.push(`**Status:** ${result.appliedSteps.every((s) => s.success) ? '✅ Success' : '⚠️ Completed with errors'}`);
  lines.push(`**Files Affected:** ${plan.filesAffected.length}`);
  lines.push(`**Total Steps Applied:** ${result.appliedSteps.length}`);
  if (result.backupDir) {
    lines.push(`**Backup Location:** \`${result.backupDir}\``);
  }
  lines.push('');

  lines.push('## 📋 Applied Steps');
  lines.push('');
  lines.push('| Rule | File | Status | Detail |');
  lines.push('|---|---|---|---|');

  for (const step of result.appliedSteps) {
    const status = step.success ? '✅ Success' : '❌ Failed';
    const detail = step.error ? `\`${step.error}\`` : 'Applied transformation';
    lines.push(`| \`${step.ruleId}\` | \`${step.filePath}\` | ${status} | ${detail} |`);
  }

  lines.push('');
  lines.push('---');
  lines.push(`*Generated by ReactPilot Migration Assistant on ${new Date().toUTCString()}*`);

  return lines.join('\n');
}
